version: '3.9'
services:
  xtr:
    container_name: xtr
    environment:
      - SERVER_PORT=8090
      - LOG_LEVEL=INFO
#      - SERVER_SSL_ENABLED=true
#      - SERVER_SSL_KEYSTORE=conf/keystore.p12
#      - SERVER_SSL_KEYSTOREPASSWORD=changeit
#      - SERVER_SSL_CERTIFICATE=conf/cert.crt
#      - SERVER_SSL_CERTIFICATEPRIVATEKEY=conf/key.key

    build:
      context: .
    ports:
      - 8080:8080
    networks:
      - xtr

networks:
  xtr:
    driver: bridge